name: Emergency 
version: 3.0
main: me.falceso.emgergeny.FrontDoor
description: Blank!
 
commands:
    falcesofronton:
        usage: /<command>
        description: derp
    falcesofrontoff:
        usage: /<command>
        description: derp
    falcesofrontreset:
        usage: /<command>
        description: derp