name: Emergency 
version: 3.0
main: me.falceso.emergency.FrontDoor
description: Emergency is a plugin to help out with kicks and bans!
 
commands:
    falcesofront:
        usage: /<command>
        description: Yea Don't you F*** try. 